### ISSUE TITLE
Doesn't work for >= Anki 2.1.38, getAudio method removed

### ISSUE THREAD

**Issue by b-money-salv** [rroessler1/speech-to-text#1] opened 2021-03-26 10:01 UTC
hi! I have the latest anki update, I get the following when I try to install this addon? I was wondering if you knew what the issue could be? TIA

![image](https://user-images.githubusercontent.com/81414705/112615036-f6949480-8e5c-11eb-8a0c-145bf8da56ee.png)

**Comment by rroessler1** [comment] 2021-03-28 03:01
Just wanted to make sure, you got this working now?

**Comment by b-money-salv** [comment] 2021-03-28 08:15
I did not mate, I’d love to be able to get this working alongside the ‘awesome TTS’ addon. Would you know if this is possible? I noticed your addon mentions that it works on the 2.1.0 version only? I’d be more than happy to use the older version if this addon works but I have no idea how to do this? Any solution you could offer would be greatly appreciated. I’m trying to get this same solution working with this, but the speech to text software is not working well at all. Thanks for responding,Curtis Sent from Mail for Windows 10 From: rroessler1Sent: Sunday, 28 March 2021 11:01 AMTo: rroessler1/speech-to-textCc: b-money-salv; State changeSubject: Re: [rroessler1/speech-to-text] addon not working? (#1) Just wanted to make sure, you got this working now?—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rroessler1** [comment] 2021-03-29 03:19
Nice, thanks for this.  It looks like Anki 2.1.43 broke this.

https://github.com/ankitects/anki/commit/ecb7c1482f72865f99a0c1e85fc17c11b297efaa#diff-986853990081ce28739e6c00724ceddf60bf593ac816ce026dcd066e41bf39f4

**Comment by rroessler1** [comment] 2021-03-29 03:27
@b-money-salv , not sure why AwesomeTTS is not working for you, unless the latest Anki update also broke that.

But for Speech-to-Text, it will work on < Anki 2.1.43.  To downgrade, for me, if you go to File -> Switch Profile, there's a button on the bottom right that says "Downgrade & Quit", that I assume will work.  Or you could always uninstall and reinstall a lower version.

I'll start fixing this to support >= 2.1.43, though I'm not positive it works on Windows at the moment.

**Comment by b-money-salv** [comment] 2021-03-29 04:46
Sorry I probably wasn’t too clear in my email, I’m not too savvy with this but I really want to get this going. So the awesome TTS does work fine on the latest version, I did notice other people were doing what you’ve said to do & downgrade this way so I’ll try this again.  Thanks a lot for getting back to me mate, I’ll let you know how I go later today.  Sent from Mail for Windows 10 From: rroessler1Sent: Monday, 29 March 2021 11:27 AMTo: rroessler1/speech-to-textCc: b-money-salv; MentionSubject: Re: [rroessler1/speech-to-text] Doesn't work for >= Anki 2.1.43, getAudio method removed ***@***.*** , not sure why AwesomeTTS is not working for you, unless the latest Anki update also broke that.But for Speech-to-Text, it will work on < Anki 2.1.43. To downgrade, for me, if you go to File -> Switch Profile, there's a button on the bottom right that says "Downgrade & Quit", that I assume will work. Or you could always uninstall and reinstall a lower version.I'll start fixing this to support >= 2.1.43, though I'm not positive it works on Windows at the moment.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rroessler1** [comment] 2021-03-29 04:49
No need to downgrade, I just finished the fix to support the latest version.  I'll release it to the Anki site within 24 hours, I'll comment here when it's uploaded.

**Comment by rroessler1** [comment] 2021-03-29 05:09
I just updated the add-on, can you try reinstalling it and confirm if it's working or not?
I'm still not sure if it works on Windows or not so your feedback would be super helpful!
I'm expecting it to have an error but a different one.

**Comment by b-money-salv** [comment] 2021-03-30 02:10
Hey mate, just had the chance to try it, so this is the new error – hopefully it’s the error you expected? Sent from Mail for Windows 10 From: rroessler1Sent: Monday, 29 March 2021 1:10 PMTo: rroessler1/speech-to-textCc: b-money-salv; MentionSubject: Re: [rroessler1/speech-to-text] Doesn't work for >= Anki 2.1.38, getAudio method removed (#1) I just updated the add-on, can you try reinstalling it and confirm if it's working or not?I'm still not sure if it works on Windows or not so your feedback would be super helpful!I'm expecting it to have an error but a different one.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by b-money-salv** [comment] 2021-03-30 02:45
Just tried to downgrade & install the 2.1.40 release to see if the outcome was any different, this was the error:  Sent from Mail for Windows 10 From: rroessler1Sent: Monday, 29 March 2021 1:10 PMTo: rroessler1/speech-to-textCc: b-money-salv; MentionSubject: Re: [rroessler1/speech-to-text] Doesn't work for >= Anki 2.1.38, getAudio method removed (#1) I just updated the add-on, can you try reinstalling it and confirm if it's working or not?I'm still not sure if it works on Windows or not so your feedback would be super helpful!I'm expecting it to have an error but a different one.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rroessler1** [comment] 2021-03-30 03:11
Sorry, I can't see the error you're posting, you might have to log into Github to post a picture (or you can just copy and paste the error).

https://github.com/rroessler1/speech-to-text/issues/1

**Comment by b-money-salv** [comment] 2021-03-30 03:15
![image](https://user-images.githubusercontent.com/81414705/112928334-048e3200-9149-11eb-9203-32862a110a80.png)
![Screenshot_75](https://user-images.githubusercontent.com/81414705/112928393-22f42d80-9149-11eb-8783-c62a72249213.png)

**Comment by b-money-salv** [comment] 2021-03-30 03:15
this was the error for 2.1.42:
![image](https://user-images.githubusercontent.com/81414705/112928459-3ef7cf00-9149-11eb-8e96-85311fd281aa.png)

**Comment by rroessler1** [comment] 2021-03-30 03:25
Thanks a lot!  Yeah, seems to be a confirmed issue on Windows, I'm looking into it now.

I'm going to close this issue, tracking the new one here: https://github.com/rroessler1/speech-to-text/issues/2

**Closed by rroessler1** 2021-03-30 03:25 UTC
